[package]
name = "rockpeek"
version = "0.1.0"
edition = "2024"

[dependencies]
rocksdb = "0.24"
clap = { version = "4.3", features = ["derive"] }
prost = "0.11"
prost-reflect = "0.12"
base64 = "0.21"
hex = "0.4.3"

